name: builder

on: pull_request

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./out/tests/coverage-unit.txt
          flags: unit,os_${{ matrix.os }}
          fail_ci_if_error: true
