name: build

on: pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        config: [windows-wcow]
        include:
          - config: windows-wcow
            os: windows
            runner: [windows, wcow]
            no_docker: "false"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: Derive pack version from branch name
        run: |
          [[ $GITHUB_REF =~ ^refs\/heads\/release/(.*)$ ]] && version=${BASH_REMATCH[1]} || version=0.0.0
          echo "PACK_VERSION=${version}" >> $GITHUB_ENV
        shell: bash
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./out/tests/coverage-unit.txt
          flags: unit,os_${{ matrix.os }}
          fail_ci_if_error: true
