name: build

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'resources/**'
      - 'CODEOWNERS'
      - 'LICENSE'
    branches:
      - main
      - 'release/**'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        config: [macos, linux, windows-lcow, windows-wcow]
        include:
          - config: macos
            os: macos
            runner: macos-latest
            no_docker: "true"
            pack_bin: pack
          - config: linux
            os: linux
            runner: ubuntu-latest
            no_docker: "false"
            pack_bin: pack
          - config: windows-lcow
            os: windows
            runner: [self-hosted, windows]
            no_docker: "false"
            pack_bin: pack.exe
          - config: windows-wcow
            os: windows
            runner: [self-hosted, windows, wcow]
            no_docker: "false"
            pack_bin: pack.exe
    runs-on: ${{ matrix.runner }}
    env:
      PACK_BIN: ${{ matrix.pack_bin }}
      NO_DOCKER: ${{ matrix.no_docker }}
    steps:
      - name: Set git to use LF and symlinks
        if: matrix.os == 'windows'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.symlinks true
      - uses: actions/checkout@v2
      - name: Derive pack version from branch name
        run: |
          [[ $GITHUB_REF =~ ^refs\/heads\/release/(.*)$ ]] && version=${BASH_REMATCH[1]} || version=0.0.0
          echo "PACK_VERSION=${version}" >> $GITHUB_ENV
        shell: bash
      - name: Set up go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.14'
      - name: Set up go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Verify
        run: make verify
      - name: Test
        env:
          TEST_COVERAGE: 1
        run: make test
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./out/tests/coverage-unit.txt
          flags: unit,os_${{ matrix.os }}
          fail_ci_if_error: true
